#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASHif [ -z “$(ps -ef | grep elasticsearch | grep -v grep)” ]
then
 client_result “Application is already stopped”
else
 kill `ps -ef | grep elasticsearch | grep -v grep | awk ‘{ print $2 }’` > /dev/null 2>&1
fi
